### ISSUE TITLE
Sample Import Fails

### ISSUE THREAD

**Issue by schaeffer** [redminehappiestminds/redmine_issues_from_excel#1]
- I'm running on  Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-80-generic x86_64):

_Environment:
  Redmine version                2.6.1.stable
  Ruby version                   1.9.3-p0 (2011-10-30) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem  
Redmine plugins:
  redmine_issues_from_excel      0.0.1
  redmine_knowledgebase          3.0.7
  redmine_mylyn_connector        2.8.2.stable
  redmine_time_tracker           0.9.18
  redmine_wktime                 1.7
  redmine_work_time              0.2.16_
- When I try to use the "Sample Excel" I get:

_Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error._
- The Redmine log file shows:

_Started GET "/redmine/projects/audireifendb/import_from_excel/download_sample.xlsx?tracker=10" for 192.168.100.7 at 2015-05-20 12:59:15 +0200
Processing by ImportFromExcelController#download_sample as XLSX
  Parameters: {"tracker"=>"10", "name_prefix"=>"project", "project_id"=>"audireifendb"}
  Current user: schaeffer (id=3)
Completed 500 Internal Server Error in 21.1ms_

ArgumentError (wrong number of arguments (2 for 1)):
  zip (2.0.2) lib/zip/zip.rb:925:in `initialize'
  axlsx (1.3.6) lib/axlsx/package.rb:113:in`new'
  axlsx (1.3.6) lib/axlsx/package.rb:113:in `to_stream'
  plugins/redmine_issues_from_excel/app/controllers/import_from_excel_controller.rb:64:in`generate_excel'
  plugins/redmine_issues_from_excel/app/controllers/import_from_excel_controller.rb:81:in `block (2 levels) in download_sample'
  actionpack (3.2.21) lib/action_controller/metal/mime_responds.rb:196:in`call'
  actionpack (3.2.21) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
  plugins/redmine_issues_from_excel/app/controllers/import_from_excel_controller.rb:79:in`download_sample'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:480:in `_run__1900638900436224770__process_action__1747017015313030684__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
 journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in`call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in`_run__927696622862334667__call__831705072956505544__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:18:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in`call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (3.0.14) lib/phusion_passenger/rack/request_handler.rb:96:in`process_request'
  passenger (3.0.14) lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  passenger (3.0.14) lib/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
  passenger (3.0.14) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.14) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in`block in handle_spawn_application'
  passenger (3.0.14) lib/phusion_passenger/utils.rb:470:in `safe_fork'
  passenger (3.0.14) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in`handle_spawn_application'
  passenger (3.0.14) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.14) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.14) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.14) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in`start'
  passenger (3.0.14) lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
  passenger (3.0.14) lib/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  passenger (3.0.14) lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
  passenger (3.0.14) lib/phusion_passenger/abstract_server_collection.rb:82:in`block in synchronize'
  internal:prelude:10:in `synchronize'
  passenger (3.0.14) lib/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  passenger (3.0.14) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.14) lib/phusion_passenger/spawn_manager.rb:132:in`spawn_application'
  passenger (3.0.14) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.14) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.14) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.14) helper-scripts/passenger-spawn-server:99:in`<main>' 
- I'm very interested in using this plugin; it looks to be exactly what I'm looking for. Can you please give me a hint of what could be wrong with my installation? Many thanks.

**Comment by redminehappiestminds** [comment]
Please use axlsx version 2.0.1 
Add a below line to your Gemfile
gem 'axlsx', '~> 2.0.1'
