### ISSUE TITLE
No link for sample excel file

### ISSUE THREAD

**Issue by fastuser** [redminehappiestminds/redmine_issues_from_excel#2]
Can you upload the sample file please ?
Do you know if this works one Redmine 3.x ?

**Comment by Narmatha** [comment]
yes. it works on redmine 3

**Comment by atopcu** [comment]
Is there a sample excel or CSV file ?

**Comment by wodash** [comment]
Its Apr 2017 - and still no sample xml file uploaded - extraordinary !

may be someone can suggest an alternative plugin?

**Comment by redminehappiestminds** [comment]
In plugin page click a sample excel link for download a sample excel file.

**Comment by fastuser** [comment]
Maybe its just me, but where is the link ?
